Add support for ARM64
0install/0install pull request #163
Opened 2020-10-12 12:58 UTC by bastianeicher

2020-10-12 13:20 UTC, talex5 requested changes

2020-10-12 13:20 UTC, talex5 commented on src/zeroinstall/arch.ml
> +    | "armhf"   -> [| "armv7l" |]
I guess this needs to list `armv6l` too.

2020-10-12 13:20 UTC, talex5 commented on src/zeroinstall/arch.ml
> +    | "aarch64"  when multiarch -> [|"armv6l"; "armv7l"|]
These lines need to be the other way around. Also, the multiarch case presumably should include `arm64`.

2020-10-12 15:34 UTC, bastianeicher commented on src/zeroinstall/arch.ml
> +    | "armhf"   -> [| "armv7l" |]
That's right. I've now added it.

2020-10-12 15:39 UTC, bastianeicher commented on src/zeroinstall/arch.ml
> +    | "aarch64"  when multiarch -> [|"armv6l"; "armv7l"|]
I've restructured it like this now:

```ocaml
| "aarch64" when multiarch -> [|"armv7l"; "armv6l"|]
| "arm64"   when multiarch -> [|"aarch64"; "armv7l"; "armv6l"|]
| "arm64" -> [|"aarch64"|]
```

What I'm trying to express is that for ARM64 machines:

- ... feeds are always expected to list the CPU type as `aarch64`.
- ... the local OS / `uname` may report the CPU as `amd64` or `aarch64`.
- ... the system can run also run ARMv6 and ARMv7 code when in 32-bit mode.

2020-10-17 11:50 UTC, talex5 commented on src/zeroinstall/arch.ml
> +    | "aarch64"  when multiarch -> [|"armv6l"; "armv7l"|]
Ah, probably the `arm64` thing should be added here instead then:

https://github.com/0install/0install/blob/5ea4b65e1eaf4719d4ec26170bcfff8d2497edb0/src/support/system.ml#L52-L63

2020-10-17 21:02 UTC, bastianeicher commented on src/zeroinstall/arch.ml
> +    | "aarch64"  when multiarch -> [|"armv6l"; "armv7l"|]
Ah, indeed! I'd completely overlooked `canonical_machines`. Adjusted the PR accordingly.

Perhaps `ppc` -> `ppc32` should also be moved here?

2020-10-24 12:48 UTC, talex5 approved these changes

2020-10-24 13:46 UTC, merged