Add support for zstd-compressed archives
0install/0install pull request #175
Opened 2021-03-07 15:39 UTC by bastianeicher

2021-03-14 16:51 UTC, talex5 reviewed
Looks good to me, except for the fallback script.

2021-03-14 16:51 UTC, talex5 commented on src/zeroinstall/archive.ml
> +          Lazy.force share_dir +/ "0install.net" +/ "unzstd"
There's no point including this fallback unless you also add a `unzstd` script in the share directory for it to run. Since the change above aborts if it's not installed, I guess this should just be `"--use-compress-program=unzstd"`.

2021-03-14 18:19 UTC, bastianeicher commented on src/zeroinstall/archive.ml
> +          Lazy.force share_dir +/ "0install.net" +/ "unzstd"
Ok, fallback removed.

2021-03-21 19:11 UTC, talex5 requested changes
Ci is failing because `unzstd` isn't defined anywhere.

2021-03-21 19:11 UTC, talex5 commented on src/zeroinstall/archive.ml
> +    | Zstd -> ["--use-compress-program=" ^ unzstd]
```suggestion
    | Zstd -> ["--use-compress-program=unzstd"]
```

2022-12-13 15:48 UTC, bastianeicher commented on src/zeroinstall/archive.ml
> +          Lazy.force share_dir +/ "0install.net" +/ "unzstd"
I've added a fallback script now, using the feed https://apps.0install.net/utils/zstd.xml.

2022-12-22 16:11 UTC, talex5 commented on src/zeroinstall/archive.ml
> +                    I need to extract it. Install the package containing it (it's probably called \"zstd\") first."
Now we can get unzstd through 0install, right? So this (and the "unxz" case above it) should be the same as the "x-lzma-compressed-tar" case I think.

2022-12-22 18:45 UTC, bastianeicher commented on src/zeroinstall/archive.ml
> +                    I need to extract it. Install the package containing it (it's probably called \"zstd\") first."
Ah yes, indeed, thank! Changed it.

2022-12-22 20:00 UTC, talex5 approved these changes
Thanks!

2022-12-22 20:00 UTC, merged